networks:
  backend-net:
    driver: bridge
  monitoring-net:
    driver: bridge

volumes:
  pgdata:             # PostgreSQL Database
  minio-data:         # MinIO Object-Storage
  sonarqube_data:     # SonarQube Database (embedded H2)
  sonarqube_logs:     # SonarQube Logs
  sonarqube_ext:      # SonarQube Extensions/Plugins
  redis-data:         # Redis Data
  simulation-uploads: # Simulation Service Uploads
  simulation-logs:    # Simulation Service Logs
  prometheus-data:    # Prometheus Data

services:
  docker-stats:
    build: ./docker-stats
    networks:
      - backend-net
      - monitoring-net  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3002/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - PROMETHEUS_URL=http://prometheus:9090

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:80"
    networks:
      - backend-net
      - monitoring-net
    depends_on:
      storage-service:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker stats

  simulation-frontend:
    build: ./simulation-frontend
    ports:
      - "${SIMULATION_FRONTEND_PORT}:3000"
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SIMULATION_FRONTEND_PORT: ${SIMULATION_FRONTEND_PORT}
      REACT_APP_API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      REACT_APP_PREDICTION_WS_URL: ${REACT_APP_PREDICTION_WS_URL}
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_MAPTILER_API_KEY: ${MAPTILER_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker stats
    labels:
      sim.group: "frontend"

  prediction-service:
    networks:
      - backend-net
      - monitoring-net
    build:
      context: ./prediction-service
      args:
        PORT: ${PREDICTION_PORT}
    depends_on:
      storage-service:
        condition: service_healthy
    environment:
      PREDICTION_PORT: ${PREDICTION_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      STORAGE_URL: ${STORAGE_URL}
    labels:
      sim.group: "prediction-service"  
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

  storage-service:
    build: ./storage-service
    networks:
      - backend-net
      - monitoring-net
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      STORAGE_URL: ${STORAGE_URL}
      STORAGE_PORT: ${STORAGE_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      CACHE_ENABLED: ${CACHE_ENABLED}
      PREDICTION_RADIUS: ${PREDICTION_RADIUS}
      USE_DIRECTIONAL_FILTER: ${USE_DIRECTIONAL_FILTER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CACHE_TTL: ${CACHE_TTL}
    expose:
      - "${STORAGE_PORT}"
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 2G
    tmpfs:
      - /tmp:size=2G,noexec,nosuid
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://storage-service:${STORAGE_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      sim.group: "storage-service"  # Label for metric filtering

  redis:
    image: redis:7-alpine
    networks:
      - backend-net
      - monitoring-net
    volumes:
      - type: volume
        source: redis-data
        target: /data
    command: >
      redis-server
      --io-threads 6
      --io-threads-do-reads yes
      --maxmemory 6gb
      --appendonly no       
      --save ""
      --tcp-keepalive 300
    ports:
      - "6379:6379"  # Expose for monitoring
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
    labels:
      sim.group: "redis"  # Label for metric filtering

  postgres:
    image: postgres:15-alpine
    networks:
      - backend-net
      - monitoring-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      sim.group: "database"

  minio:
    image: minio/minio:latest
    networks:
      - backend-net
      - monitoring-net
    ports:
      - "${MINIO_PORT}:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      sim.group: "minio"  # Label for metric filtering

  # cAdvisor for container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    networks:
      - monitoring-net
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    command:
      - '--housekeeping_interval=10s'
      - '--docker_only=true'
      - '--store_container_labels=false'
      - '--whitelisted_container_labels=sim.group'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    networks:
      - monitoring-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  sonarqube:
    image: sonarqube:9.9-community
    networks:
      - monitoring-net
    ports:
      - "${SONARQUBE_PORT}:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_ext:/opt/sonarqube/extensions