// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/storage/objects": {
            "get": {
                "description": "Gets all 3D objects stored in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "List all 3D objects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Object"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Object": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "original_filename": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "storage_key": {
                    "type": "string"
                },
                "uploaded_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "api/storage",
	Schemes:          []string{},
	Title:            "Storage Service API",
	Description:      "Service for managing 3D objects storage and retrieval",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
