definitions:
  models.Object:
    properties:
      content_type:
        type: string
      id:
        type: string
      original_filename:
        type: string
      size:
        type: integer
      storage_key:
        type: string
      uploaded_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/objects:
    get:
      consumes:
      - application/json
      description: Gets all 3D objects stored in the system.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Object'
            type: array
      summary: List all 3D objects
      tags:
      - objects
swagger: "2.0"
