scrape_configs:
  - job_name: cadvisor
    scrape_interval: 1s
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - action: labelmap
        regex: ^container_label_(sim\..+)$   # sim.group etc.
